version: "3.7"

services:

  workout-portal-ui:
    build:
      context: .
    container_name: workout-portal-ui
    restart: always
    ports:
      - "4200:4200"   # app port
      - "49153:49153" # live-reload-port
    command: ["start"]
    depends_on:
      - workout-portal-api-service
