version: "3.7"

services:

  workout-portal-api-service:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    container_name: workout-portal-api-service
    depends_on:
      - workout-portal-api-db
    links:
      - workout-portal-api-db

  workout-portal-api-db:
    image: postgres:10
    restart: always
    container_name: workout-portal-api-db
    environment:
      - POSTGRES_USER=django_learning
      - POSTGRES_PASSWORD=django_learning
      - POSTGRES_DB=django_learning

