version: "3.7"

networks:
  workout-portal-local:
    name: workout-portal-local

services:

  workout-portal-api-service:
    networks:
      - workout-portal-local
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    container_name: workout-portal-api-service
