version: "3.7"

services:

  workout-portal-api-service:
    build:
      context: .
    volumes:
      - ./django_learning:/usr/src/app/django_learning
      - ./workout_portal:/usr/src/app/workout_portal

  workout-portal-ui:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/usr/src/app/frontend/src